import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { Navbar } from "./components/Navbar";
import { Inter, Lato, Urbanist, Titillium_Web, Amaranth } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "./components/Footer";
import { SocialHandles } from "./components/SocialHandles";
import Logo from './public/Logo.svg'
import Head from "next/head";

// Load custom fonts

const lato = Lato({ weight: "400", subsets: ["latin"] });
const urbanist = Urbanist({ weight: "400", subsets: ["latin"] });
const titillium_Web = Titillium_Web({ weight: "400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight: "400", subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata: Metadata = {
  title: "WebMetrix",
  description: "Generated by Anas Nadkar",
  icons: Logo
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by Anas Nadkar" />
        <meta name="keywords" content="WebMetrix, code snippets, web development" /> {/* Update keywords */}
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://yourwebsite.com/" /> {/* Change to your website URL */}
        <meta property="og:title" content="WebMetrix" />
        <meta property="og:description" content="Generated by Anas Nadkar" />
        <meta property="og:url" content="https://yourwebsite.com/" /> {/* Change to your website URL */}
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://yourwebsite.com/path-to-your-image.jpg" /> {/* Ensure this image exists */}
      </Head>
      <body
        className={cn(titillium_Web.className)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative max-w-7xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
            {/* Navbar */}
            <Navbar />
            <SocialHandles />
            {/* Page Content */}
            <main className="pt-16">
              {children}
            </main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
